INSERT INTO `assessment_testing`.`studio` (`studio_name`) VALUES ("Client Services & Operations Support");
INSERT INTO `assessment_testing`.`studio` (`studio_name`) VALUES ("Cloud & Infrastructure");
INSERT INTO `assessment_testing`.`studio` (`studio_name`) VALUES ("Cybersecurity");
INSERT INTO `assessment_testing`.`studio` (`studio_name`) VALUES ("Data & AI");
INSERT INTO `assessment_testing`.`studio` (`studio_name`) VALUES ("Digital Business Transformation");
INSERT INTO `assessment_testing`.`studio` (`studio_name`) VALUES ("ITSM");
INSERT INTO `assessment_testing`.`studio` (`studio_name`) VALUES ("Management Consulting");
INSERT INTO `assessment_testing`.`studio` (`studio_name`) VALUES ("Software Engineering");
INSERT INTO `assessment_testing`.`studio` (`studio_name`) VALUES ("TAG - Marketing");
INSERT INTO `assessment_testing`.`studio` (`studio_name`) VALUES ("Technology Strategy & Architecture");
INSERT INTO `assessment_testing`.`studio` (`studio_name`) VALUES ("zAdministration");

INSERT INTO `assessment_testing`.`discipline` (`discipline_name`) VALUES ("Agile Transformation");
INSERT INTO `assessment_testing`.`discipline` (`discipline_name`) VALUES ("AI & Data Science");
INSERT INTO `assessment_testing`.`discipline` (`discipline_name`) VALUES ("Architecture & Development");
INSERT INTO `assessment_testing`.`discipline` (`discipline_name`) VALUES ("Business Program Management & Analysis");
INSERT INTO `assessment_testing`.`discipline` (`discipline_name`) VALUES ("Client Services");
INSERT INTO `assessment_testing`.`discipline` (`discipline_name`) VALUES ("Cloud Solutions");
INSERT INTO `assessment_testing`.`discipline` (`discipline_name`) VALUES ("Data Analytics & Visualization");
INSERT INTO `assessment_testing`.`discipline` (`discipline_name`) VALUES ("Data Architecture & Engineering");
INSERT INTO `assessment_testing`.`discipline` (`discipline_name`) VALUES ("DevSecOps");
INSERT INTO `assessment_testing`.`discipline` (`discipline_name`) VALUES ("Digital Delivery Management");
INSERT INTO `assessment_testing`.`discipline` (`discipline_name`) VALUES ("Enterprise Engineering");
INSERT INTO `assessment_testing`.`discipline` (`discipline_name`) VALUES ("Human Experience Design");
INSERT INTO `assessment_testing`.`discipline` (`discipline_name`) VALUES ("IT Cybersecurity");
INSERT INTO `assessment_testing`.`discipline` (`discipline_name`) VALUES ("Lab Services");
INSERT INTO `assessment_testing`.`discipline` (`discipline_name`) VALUES ("Leadership Advisory");
INSERT INTO `assessment_testing`.`discipline` (`discipline_name`) VALUES ("Learning & Development");
INSERT INTO `assessment_testing`.`discipline` (`discipline_name`) VALUES ("Operations & Support");
INSERT INTO `assessment_testing`.`discipline` (`discipline_name`) VALUES ("Organizational Effectiveness & Change");
INSERT INTO `assessment_testing`.`discipline` (`discipline_name`) VALUES ("Product Strategy & Analysis");
INSERT INTO `assessment_testing`.`discipline` (`discipline_name`) VALUES ("Service Management");
INSERT INTO `assessment_testing`.`discipline` (`discipline_name`) VALUES ("Site Reliability");
INSERT INTO `assessment_testing`.`discipline` (`discipline_name`) VALUES ("Solution Architecture");
INSERT INTO `assessment_testing`.`discipline` (`discipline_name`) VALUES ("TAG - Marketing");
INSERT INTO `assessment_testing`.`discipline` (`discipline_name`) VALUES ("Technology Strategy");
INSERT INTO `assessment_testing`.`discipline` (`discipline_name`) VALUES ("Test & Test Automation");
INSERT INTO `assessment_testing`.`discipline` (`discipline_name`) VALUES ("zAdministration");

INSERT INTO `assessment_testing`.`assessment_form` (`assessment_form_title`) VALUES ("TestDeliveryExcellence001");

INSERT INTO `assessment_testing`.`category` (`category_name`, `category_descriptoin`) VALUES ( "Stakeholder Relations", "");
INSERT INTO `assessment_testing`.`category` (`category_name`, `category_descriptoin`) VALUES ( "Test Management", "");
INSERT INTO `assessment_testing`.`category` (`category_name`, `category_descriptoin`) VALUES ( "Test Professionalism", "Tester professionalism includes the right mix of the various skills, competences, disciplines, functions and knowledge that are necessary to perform test activities to the levels expected.");

INSERT INTO `assessment_testing`.`assessment_form_categories` (`assessment_form_id`, `category_id`) VALUES (1,1);
INSERT INTO `assessment_testing`.`assessment_form_categories` (`assessment_form_id`, `category_id`) VALUES (1,2);
INSERT INTO `assessment_testing`.`assessment_form_categories` (`assessment_form_id`, `category_id`) VALUES (1,3);

INSERT INTO `assessment_testing`.`key_areas` (`key_area_name`, `key_area_description`) VALUES ("Stakeholder commitment", "Committed and proactive stakeholders create good conditions for efficient communication and cooperation.");
INSERT INTO `assessment_testing`.`key_areas` (`key_area_name`, `key_area_description`) VALUES ("Degree of involvement", "Tight involvement of testing in the project helps to improve the product quality from the beginning, and helps to keep test activities off the project’s critical path.");
INSERT INTO `assessment_testing`.`key_areas` (`key_area_name`, `key_area_description`) VALUES ("Test strategy", "The test strategy guides the test process towards an optimal allocation of effort and resources.");
INSERT INTO `assessment_testing`.`key_areas` (`key_area_name`, `key_area_description`) VALUES ("Test organization", "A test organization meets the needs of projects for test resources, test products and test services.");
INSERT INTO `assessment_testing`.`key_areas` (`key_area_name`, `key_area_description`) VALUES ("Communication", "Distinct communication ensures common understanding and alignment of expectations between all parties involved.");
INSERT INTO `assessment_testing`.`key_areas` (`key_area_name`, `key_area_description`) VALUES ("Reporting", "Reporting provides stakeholders with insight to support the decision making process and test project accounting.");
INSERT INTO `assessment_testing`.`key_areas` (`key_area_name`, `key_area_description`) VALUES ("Test process management", "Managing the test process maximizes the execution of the test assignment within the required time, costs, and results.");
INSERT INTO `assessment_testing`.`key_areas` (`key_area_name`, `key_area_description`) VALUES ("Estimating and planning", "The proper use of appropriate estimating and planning techniques makes the test process planning and estimating predictable and reliable.");
INSERT INTO `assessment_testing`.`key_areas` (`key_area_name`, `key_area_description`) VALUES ("Metrics", "Metrics provide objectivity by quantifying observations.");
INSERT INTO `assessment_testing`.`key_areas` (`key_area_name`, `key_area_description`) VALUES ("Defect management", "Defect management treats defects both at an individual level and at a group level where root causes are analyzed and guidelines are available.");
INSERT INTO `assessment_testing`.`key_areas` (`key_area_name`, `key_area_description`) VALUES ("Testware management", "Testware managememnt ensures coherence between test artifacts, and between test artifacts and their related design documents.");
INSERT INTO `assessment_testing`.`key_areas` (`key_area_name`, `key_area_description`) VALUES ("Methodology practice", "A described method for testing directs and supports the test projects.");
INSERT INTO `assessment_testing`.`key_areas` (`key_area_name`, `key_area_description`) VALUES ("Tester professionalism", "Tester professionalism includes the right mix of the various skills, competences, disciplines, functions and knowledge that are necessary to perform test activities to the levels expected.");
INSERT INTO `assessment_testing`.`key_areas` (`key_area_name`, `key_area_description`) VALUES ("Test case design", "Test case design directs test execution to search for defects according to the test strategy.");
INSERT INTO `assessment_testing`.`key_areas` (`key_area_name`, `key_area_description`) VALUES ("Test tools", "Test tools enable or accelerate specific test activities.");
INSERT INTO `assessment_testing`.`key_areas` (`key_area_name`, `key_area_description`) VALUES ("Test environment	", "The test environment is explicitly designed, implemented and maintained with the goals of the test level in mind.");

INSERT INTO `assessment_testing`.`assessment_form_key_areas` (`assessment_form_id`, `category_id`, `key_area_id`, `sequence`) VALUES (1,1,1,1);
INSERT INTO `assessment_testing`.`assessment_form_key_areas` (`assessment_form_id`, `category_id`, `key_area_id`, `sequence`) VALUES (1,1,3,2);
INSERT INTO `assessment_testing`.`assessment_form_key_areas` (`assessment_form_id`, `category_id`, `key_area_id`, `sequence`) VALUES (1,1,4,3);
INSERT INTO `assessment_testing`.`assessment_form_key_areas` (`assessment_form_id`, `category_id`, `key_area_id`, `sequence`) VALUES (1,1,5,4);
INSERT INTO `assessment_testing`.`assessment_form_key_areas` (`assessment_form_id`, `category_id`, `key_area_id`, `sequence`) VALUES (1,1,6,5);
INSERT INTO `assessment_testing`.`assessment_form_key_areas` (`assessment_form_id`, `category_id`, `key_area_id`, `sequence`) VALUES (1,1,7,6);
INSERT INTO `assessment_testing`.`assessment_form_key_areas` (`assessment_form_id`, `category_id`, `key_area_id`, `sequence`) VALUES (1,2,8,1);
INSERT INTO `assessment_testing`.`assessment_form_key_areas` (`assessment_form_id`, `category_id`, `key_area_id`, `sequence`) VALUES (1,2,9,2);
INSERT INTO `assessment_testing`.`assessment_form_key_areas` (`assessment_form_id`, `category_id`, `key_area_id`, `sequence`) VALUES (1,2,10,3);
INSERT INTO `assessment_testing`.`assessment_form_key_areas` (`assessment_form_id`, `category_id`, `key_area_id`, `sequence`) VALUES (1,2,11,4);
INSERT INTO `assessment_testing`.`assessment_form_key_areas` (`assessment_form_id`, `category_id`, `key_area_id`, `sequence`) VALUES (1,2,12,5);
INSERT INTO `assessment_testing`.`assessment_form_key_areas` (`assessment_form_id`, `category_id`, `key_area_id`, `sequence`) VALUES (1,4,13,1);
INSERT INTO `assessment_testing`.`assessment_form_key_areas` (`assessment_form_id`, `category_id`, `key_area_id`, `sequence`) VALUES (1,4,14,2);
INSERT INTO `assessment_testing`.`assessment_form_key_areas` (`assessment_form_id`, `category_id`, `key_area_id`, `sequence`) VALUES (1,4,15,3);
INSERT INTO `assessment_testing`.`assessment_form_key_areas` (`assessment_form_id`, `category_id`, `key_area_id`, `sequence`) VALUES (1,4,16,4);
INSERT INTO `assessment_testing`.`assessment_form_key_areas` (`assessment_form_id`, `category_id`, `key_area_id`, `sequence`) VALUES (1,4,17,5);

INSERT INTO `assessment_testing`.`maturity_level` (`maturity_level_name`) VALUES ("Controlled");
INSERT INTO `assessment_testing`.`maturity_level` (`maturity_level_name`) VALUES ("Efficient");
INSERT INTO `assessment_testing`.`maturity_level` (`maturity_level_name`) VALUES ("Optimizing");

INSERT INTO `assessment_testing`.`checkpoints` (`checkpoint_name`) VALUES ("The principal stakeholder is defined (not necessarily documented) and known to the testers.");
INSERT INTO `assessment_testing`.`checkpoints` (`checkpoint_name`) VALUES ("Budget for test resources is granted by and negotiable with the principal stakeholder.");
INSERT INTO `assessment_testing`.`checkpoints` (`checkpoint_name`) VALUES ("Stakeholders actually deliver the committed resources.");
INSERT INTO `assessment_testing`.`checkpoints` (`checkpoint_name`) VALUES ("The principal stakeholder is responsible for a documented product risk analysis (the input for the test strategy).");
INSERT INTO `assessment_testing`.`checkpoints` (`checkpoint_name`) VALUES ("All relevant stakeholder are defined (not necessarily documented) and known to the testers.");
INSERT INTO `assessment_testing`.`checkpoints` (`checkpoint_name`) VALUES ("Stakeholders actively acquire information on the quality of both the test process and the test object.");
INSERT INTO `assessment_testing`.`checkpoints` (`checkpoint_name`) VALUES ("The stakeholders proactively take action on aspects that affect the test process. This includes changes in the delivery sequence of the test object and changes in the project scope.");
INSERT INTO `assessment_testing`.`checkpoints` (`checkpoint_name`) VALUES ("Line management acknowledges that test process improvement comes with the need for increased learning time for which resources are provided.");
INSERT INTO `assessment_testing`.`checkpoints` (`checkpoint_name`) VALUES ("Stakeholders are willing to adapt their way of working to suit the test process. This includes the software development and requirements management.");
INSERT INTO `assessment_testing`.`checkpoints` (`checkpoint_name`) VALUES ("An adapted way of working by the stakeholder to suit demands of the test process is jointly evaluated by the test organization and the stakeholder.");

INSERT INTO `assessment_testing`.`assessment_form_checkpoints` (`checkpoint_id`, `sequence`, `maturity_level_id`, `key_area_id`, `assessment_form_id`) VALUES (1,"01.c.1",1,1,1);
INSERT INTO `assessment_testing`.`assessment_form_checkpoints` (`checkpoint_id`, `sequence`, `maturity_level_id`, `key_area_id`, `assessment_form_id`) VALUES (2,"01.c.2",1,1,1);
INSERT INTO `assessment_testing`.`assessment_form_checkpoints` (`checkpoint_id`, `sequence`, `maturity_level_id`, `key_area_id`, `assessment_form_id`) VALUES (3,"01.c.3",1,1,1);
INSERT INTO `assessment_testing`.`assessment_form_checkpoints` (`checkpoint_id`, `sequence`, `maturity_level_id`, `key_area_id`, `assessment_form_id`) VALUES (4,"01.c.4",1,1,1);
INSERT INTO `assessment_testing`.`assessment_form_checkpoints` (`checkpoint_id`, `sequence`, `maturity_level_id`, `key_area_id`, `assessment_form_id`) VALUES (5,"01.e.1",2,1,1);
INSERT INTO `assessment_testing`.`assessment_form_checkpoints` (`checkpoint_id`, `sequence`, `maturity_level_id`, `key_area_id`, `assessment_form_id`) VALUES (6,"01.e.2",2,1,1);
INSERT INTO `assessment_testing`.`assessment_form_checkpoints` (`checkpoint_id`, `sequence`, `maturity_level_id`, `key_area_id`, `assessment_form_id`) VALUES (7,"01.e.3",2,1,1);
INSERT INTO `assessment_testing`.`assessment_form_checkpoints` (`checkpoint_id`, `sequence`, `maturity_level_id`, `key_area_id`, `assessment_form_id`) VALUES (8,"01.o.1",3,1,1);
INSERT INTO `assessment_testing`.`assessment_form_checkpoints` (`checkpoint_id`, `sequence`, `maturity_level_id`, `key_area_id`, `assessment_form_id`) VALUES (9,"01.o.2",3,1,1);
INSERT INTO `assessment_testing`.`assessment_form_checkpoints` (`checkpoint_id`, `sequence`, `maturity_level_id`, `key_area_id`, `assessment_form_id`) VALUES (10,"01.o.3",3,1,1);

SELECT * FROM `assessment_testing`.`studio`;
SELECT * FROM `assessment_testing`.`discipline`;
SELECT * FROM `assessment_testing`.`assessment_form`;
SELECT * FROM `assessment_testing`.`category`; 
SELECT * FROM `assessment_testing`.`assessment_form_categories`;
SELECT * FROM `assessment_testing`.`key_areas`;
SELECT * FROM `assessment_testing`.`assessment_form_key_areas`;
SELECT * FROM `assessment_testing`.`maturity_level`;
SELECT * FROM `assessment_testing`.`checkpoints`;
SELECT * FROM `assessment_testing`.`assessment_form_checkpoints`;

DELETE FROM `assessment_testing`.`studio`;
DELETE FROM `assessment_testing`.`discipline`;
DELETE FROM `assessment_testing`.`assessment_form`;
DELETE FROM `assessment_testing`.`category`; 
DELETE FROM `assessment_testing`.`assessment_form_categories`;
DELETE FROM `assessment_testing`.`key_areas`;
DELETE FROM `assessment_testing`.`assessment_form_key_areas`;
DELETE FROM `assessment_testing`.`maturity_level`;
DELETE FROM `assessment_testing`.`checkpoint`;
DELETE FROM `assessment_testing`.`assessment_form_checkpoints`;
